version: "3"
services:
  frontend:
    container_name: glossary_web
    build:
      context: ./client
      dockerfile: Dockerfile
    image: glossary/glossary_web
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
      - /src/app/node_modules
  backend:
    container_name: glossary_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: glossary/glossary_server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - /src/app/node_modules
